#
# GitLab example CI/CD script
# See https://docs.gitlab.com/ee/ci/yaml/README.html
#
# Secure Variables like $DB_PASSWORD can added by going to your
# project’s Settings ➔ CI / CD ➔ Variables on the GitLab website.
#
image: node:latest

before_script:
  - npm install -g firebase-tools

stages:
  - test
  - metrics
  - deploy

cache:
  key: $CI_COMMIT_REF_SLUG
  paths:
    - node_modules/

#
# Global variables
#
variables:
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_DRIVER: overlay2

#
# Run unit tests
#
unittests:
  image: markhobson/node-chrome:latest
  stage: test
  variables:
    NODE_ENV: development
    # DB_USER: $DB_USER
    # DB_PASSWORD: $DB_PASSWORD
    # DB_HOST: $DB_HOST
    # DB_PORT: $DB_PORT
    # DB_DATABASE: $DB_DATABASE
  before_script:
    - npm i --no-optional
  script:
    - npm run test
    # - npm run sonar

#end2end:
#  image: markhobson/node-chrome:latest
#  stage: test
#  variables:
#    NODE_ENV: development
#  before_script:
#    - rm -rf node_modules
#    - rm -f package-lock.json
#    - npm i
#  script:
##    - node ./node_modules/protractor/bin/webdriver-manager update --versions.chrome=76.0.3809.100
##    - node ./node_modules/protractor/bin/webdriver-manager update --versions.chrome=80.0.3987.106
#    - npm run e2e

production:
  stage: deploy
  image: markhobson/node-chrome:latest
  before_script:
    - npm i --no-optional
  script:
    - npm run build
    - firebase deploy --token $FIREBASE_TOKEN
  only:
    - master
